---
- hosts: local
  become: true
  tasks:
    - name: instalar java
      yum: name=java state=latest
    
    - name: Extract tar
      ansible.builtin.unarchive:
        src: git-2.30.0.tar.gz
        dest: /tmp/git-2.30.0
