---
- hosts: server2
  tasks:
#   - name: Remover GIT
#     yum: 
#       name: git
#       state: absent
#       autoremove: true
 #     notify:
 #       - "GIT Removido"

    - name: instalar java
      yum: name=java state=latest
    
    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
    
    - name: Install paquetitos
      yum:   
        name:
          - gettext-devel
          - openssl-devel
          - perl-CPAN
          - perl-devel
          - zlib-devel   

    - name: Download git
      get_url:
        #url: http://192.168.0.57:8081/repository/alm/git/2.30.0/git-2.30.0.tar.gz
        #winpro64reabkp3
        url: http://192.168.0.72:8081/repository/alm/git/2.30.0/git-2.30.0.tar.gz
        dest: /tmp/git-2.30.0.tar.gz
        #checksum: sha256:8db4edd1a0a74ebf4b78aed3f9e25c8f2a7db3c00b1aaee94d1e9834fae24e6

    - name: Extract tar.gz
      #ansible.builtin.unarchive:
      unarchive:
        src: /tmp/git-2.30.0.tar.gz
        dest: /tmp
        remote_src: yes

    - name: make configure
      shell: chdir=/tmp/git-2.30.0/ make configure

    - name: ./configure --prefix=/usr/local 
      shell: chdir=/tmp/git-2.30.0/ ./configure --prefix=/usr/local

    - name: make install
      shell: chdir=/tmp/git-2.30.0/ make install

    - name: Remover GIT
      yum:
        name: git
        state: absent
        autoremove: true
#   notify:
#     - "GIT Removido"

#    - name: git version
#      shell: echo | git --version

#  handlers:       
#    - name : GIT Removido
#      shell: uname -r
#      service: name=httpd state=stopped
