---
- hosts: RH8_3
  tasks:
    - name: Remover GIT
      yum: 
        name: git
        state: absent
        autoremove: true
 #     notify:
 #       - "GIT Removido"

 #   - name: instalar java
 #     yum: name=java state=latest
    
    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
    
    - name: Install paquetitos
      yum:   
        name:
          - gettext-devel
          - openssl-devel
          - perl-CPAN
          - perl-devel
          - zlib-devel   

    - name: Download cloudbees.zip
      get_url:
        url: http://192.168.0.57:8081/repository/alm/cloudbees/v1/cloudbees.zip
        dest: /tmp/cloudbees.zip
        checksum: sha256:60dc66f273b00397163493e10575ccd81f04b5cac7f8e288a97ba37d24092622

    - name: Extract tar.gz
      ansible.builtin.unarchive:
        src: git-2.30.0.tar.gz
        dest: /tmp

    - name: make configure
      shell: chdir=/tmp/git-2.30.0/ make configure

    - name: ./configure --prefix=/usr/local 
      shell: chdir=/tmp/git-2.30.0/ ./configure --prefix=/usr/local

    - name: make install
      shell: chdir=/tmp/git-2.30.0/ make install

    - name: git version
      shell: echo | git --version




#  handlers:       
#    - name : GIT Removido
#      shell: uname -r
#      service: name=httpd state=stopped
